"""empty message

Revision ID: 08b10fe7dd51
Revises: 4e6db243576b
Create Date: 2018-01-08 08:33:14.303658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b10fe7dd51'
down_revision = '4e6db243576b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('countryid', sa.Integer(), nullable=True))
    op.drop_constraint('city_ibfk_1', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'country', ['countryid'], ['id'])
    op.drop_column('city', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_ibfk_1', 'city', 'country', ['country'], ['id'])
    op.drop_column('city', 'countryid')
    # ### end Alembic commands ###
