"""empty message

Revision ID: 216350249aae
Revises: ed4793906050
Create Date: 2018-01-10 07:30:43.829202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '216350249aae'
down_revision = 'ed4793906050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'label',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    op.alter_column('city', 'pinyin',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=32),
               nullable=False)
    op.alter_column('city', 'zip',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'zip',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=16),
               nullable=True)
    op.alter_column('city', 'pinyin',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=32),
               nullable=True)
    op.alter_column('city', 'label',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    # ### end Alembic commands ###
