"""empty message

Revision ID: 37299923d9ec
Revises: 0ff11d98cf70
Create Date: 2018-01-16 20:58:34.978023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37299923d9ec'
down_revision = '0ff11d98cf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'pictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###
