"""empty message

Revision ID: 3e6e7b86a9ee
Revises: 216350249aae
Create Date: 2018-01-16 09:08:10.889597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e6e7b86a9ee'
down_revision = '216350249aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shop_comments')
    op.drop_table('hotels_copy')
    op.drop_table('users_copy')
    op.drop_table('country_copy')
    op.drop_table('hotel_comments_copy')
    op.drop_table('food_comments')
    op.drop_table('spot_comments_copy')
    op.drop_table('alembic_version_copy')
    op.drop_table('food_comments_copy')
    op.drop_table('questions_copy')
    op.drop_table('spots_copy')
    op.drop_table('hotel_comments')
    op.drop_table('spot_comments')
    op.drop_table('city_copy')
    op.drop_table('experience_copy')
    op.drop_table('shop_comments_copy')
    op.drop_table('foods_copy')
    op.drop_table('shops_copy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('describe', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('adress', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='shops_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('foods_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('describe', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('adress', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='foods_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('shop_comments_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('shopid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shopid'], ['shops.id'], name='shop_comments_copy_ibfk_2'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='shop_comments_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('experience_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_bin', length=30), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='experience_copy_ibfk_1'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='experience_copy_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('city_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('countryid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('label', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('pinyin', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('zip', mysql.VARCHAR(collation='utf8_bin', length=16), nullable=False),
    sa.ForeignKeyConstraint(['countryid'], ['country.id'], name='city_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('spot_comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('spotid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spotid'], ['spots.id'], name='spot_comments_ibfk_3'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='spot_comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hotel_comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hotelid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotelid'], ['hotels.id'], name='hotel_comments_ibfk_3'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='hotel_comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('spots_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('detail', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('adress', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('price', mysql.VARCHAR(charset='utf8', length=11), server_default=sa.text("'100'"), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='spots_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('questions_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('qid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8_bin', length=30), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('pictures', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='questions_copy_ibfk_1'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='questions_copy_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('food_comments_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('foodid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['foodid'], ['foods.id'], name='food_comments_copy_ibfk_2'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='food_comments_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('alembic_version_copy',
    sa.Column('version_num', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('spot_comments_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('spotid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spotid'], ['spots.id'], name='spot_comments_copy_ibfk_2'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='spot_comments_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('food_comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('foodid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['foodid'], ['foods.id'], name='food_comments_ibfk_3'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='food_comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hotel_comments_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hotelid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotelid'], ['hotels.id'], name='hotel_comments_copy_ibfk_2'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='hotel_comments_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('country_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('mail', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hotels_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('describe', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('adress', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pictures', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name='hotels_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('shop_comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('shopid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shopid'], ['shops.id'], name='shop_comments_ibfk_3'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='shop_comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
