"""empty message

Revision ID: 4e6db243576b
Revises: dd34e75912ef
Create Date: 2018-01-08 08:32:23.844220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e6db243576b'
down_revision = 'dd34e75912ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('experience_ibfk_1', 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'users', ['uid'], ['id'])
    op.drop_column('experience', 'auth')
    op.add_column('questions', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('questions_ibfk_1', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['uid'], ['id'])
    op.drop_column('questions', 'auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('auth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_ibfk_1', 'questions', 'users', ['auth'], ['id'])
    op.drop_column('questions', 'uid')
    op.add_column('experience', sa.Column('auth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key('experience_ibfk_1', 'experience', 'users', ['auth'], ['id'])
    op.drop_column('experience', 'uid')
    # ### end Alembic commands ###
