"""empty message

Revision ID: 5a749c4aacfb
Revises: 08b10fe7dd51
Create Date: 2018-01-08 08:34:10.855445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a749c4aacfb'
down_revision = '08b10fe7dd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_comments', sa.Column('foodid', sa.Integer(), nullable=True))
    op.drop_constraint('food_comments_ibfk_1', 'food_comments', type_='foreignkey')
    op.create_foreign_key(None, 'food_comments', 'foods', ['foodid'], ['id'])
    op.drop_column('food_comments', 'food')
    op.add_column('hotel_comments', sa.Column('hotelid', sa.Integer(), nullable=True))
    op.drop_constraint('hotel_comments_ibfk_1', 'hotel_comments', type_='foreignkey')
    op.create_foreign_key(None, 'hotel_comments', 'hotels', ['hotelid'], ['id'])
    op.drop_column('hotel_comments', 'hotel')
    op.add_column('shop_comments', sa.Column('shopid', sa.Integer(), nullable=True))
    op.drop_constraint('shop_comments_ibfk_1', 'shop_comments', type_='foreignkey')
    op.create_foreign_key(None, 'shop_comments', 'shops', ['shopid'], ['id'])
    op.drop_column('shop_comments', 'shop')
    op.add_column('spot_comments', sa.Column('spotid', sa.Integer(), nullable=True))
    op.drop_constraint('spot_comments_ibfk_1', 'spot_comments', type_='foreignkey')
    op.create_foreign_key(None, 'spot_comments', 'spots', ['spotid'], ['id'])
    op.drop_column('spot_comments', 'spot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_comments', sa.Column('spot', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'spot_comments', type_='foreignkey')
    op.create_foreign_key('spot_comments_ibfk_1', 'spot_comments', 'spots', ['spot'], ['id'])
    op.drop_column('spot_comments', 'spotid')
    op.add_column('shop_comments', sa.Column('shop', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shop_comments', type_='foreignkey')
    op.create_foreign_key('shop_comments_ibfk_1', 'shop_comments', 'shops', ['shop'], ['id'])
    op.drop_column('shop_comments', 'shopid')
    op.add_column('hotel_comments', sa.Column('hotel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hotel_comments', type_='foreignkey')
    op.create_foreign_key('hotel_comments_ibfk_1', 'hotel_comments', 'hotels', ['hotel'], ['id'])
    op.drop_column('hotel_comments', 'hotelid')
    op.add_column('food_comments', sa.Column('food', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'food_comments', type_='foreignkey')
    op.create_foreign_key('food_comments_ibfk_1', 'food_comments', 'foods', ['food'], ['id'])
    op.drop_column('food_comments', 'foodid')
    # ### end Alembic commands ###
