"""empty message

Revision ID: ed4793906050
Revises: 5a749c4aacfb
Create Date: 2018-01-10 07:12:18.100779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4793906050'
down_revision = '5a749c4aacfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('label', sa.String(length=64), nullable=True))
    op.add_column('city', sa.Column('pinyin', sa.String(length=32), nullable=True))
    op.add_column('city', sa.Column('zip', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'zip')
    op.drop_column('city', 'pinyin')
    op.drop_column('city', 'label')
    # ### end Alembic commands ###
